### PR TITLE
refactor(lib): fixing ts issues

### LINKED ISSUE #11: Ensure TypeScript builds without errors
First quick conversion wasn't perfect, it still doesn't compile.

At this stage it's fine to use `any` and `ts-ignore`, we can cleanup in a next step.

### PR DESCRIPTION
**Pull request by H4ad**
## Changes

Fixes #11

Also, I added [tsup](https://tsup.egoist.dev/) to support dual package publish (commonjs & esm).

## Checklist

- [x] Apply one of following labels; `major`, `minor`, `patch` or `skip-release`
- [x] I've updated the documentation, or no changes were necessary
- [x] I've updated the tests, or no changes were necessary

### CODE REVIEW

File: lib/yauzl-ts/RandomAccessReader.ts [hunk 1]
```diff
@@ -1,96 +1,112 @@
...
+      return this
+    }
+
+    const byteCounter = new AssertByteCountStream(end - start)
+    refUnrefFilter.on('error', function (err) {
+      setImmediate(function () {
+        if (!destroyed) byteCounter.emit('error', err)
+      })
+    })
+    byteCounter.destroy = function () {
```
Comment (kibertoad) [inline lib/yauzl-ts/RandomAccessReader.ts:72]: it's a bit of a code smell to inject new methods into a class. Can we make `destroy` a permanent method and pass necessary parameters via fields on an object instead?

doesn't have to be done in this PR, just a ToDo would suffice

File: package.json [hunk 2]
```diff
@@ -42,6 +56,7 @@
     "eslint-plugin-import": "^2.29.1",
     "eslint-plugin-vitest": "^0.3.20",
     "prettier": "^3.2.4",
+    "tsup": "^8.0.1",
```
Comment (kibertoad) [inline package.json:59]: nice!

**Review by kibertoad — APPROVED** [review]
Great job!

**Comment by kibertoad** [comment]
Merging, as it's better to postpone any runtime code changes until we have tests running, we can address class mutation later. I'll create a ticket.
